# Generated by Django 5.0.1 on 2024-02-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
